"""Add ssh_private_key field to users

Revision ID: 706d69dab38f
Revises: e5ca68a75faa
Create Date: 2025-08-26 02:37:03.289812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706d69dab38f'
down_revision = 'e5ca68a75faa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ssh_private_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ssh_private_key')
    # ### end Alembic commands ###