"""update_tasks_table_structure

Revision ID: b89a73584198
Revises: ba1972ae4ecb
Create Date: 2025-08-26 01:55:51.029178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b89a73584198'
down_revision = 'ba1972ae4ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=True))
    op.add_column('tasks', sa.Column('output', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('exit_code', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('task_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    op.drop_column('tasks', 'result')
    op.drop_column('tasks', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('error_message', mysql.TEXT(), nullable=True))
    op.add_column('tasks', sa.Column('result', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_column('tasks', 'task_metadata')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'scheduled_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'duration')
    op.drop_column('tasks', 'progress')
    op.drop_column('tasks', 'exit_code')
    op.drop_column('tasks', 'error')
    op.drop_column('tasks', 'output')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###