"""Add environment variables to projects

Revision ID: bf4c0f13280e
Revises: 706d69dab38f
Create Date: 2025-08-26 02:37:20.671254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4c0f13280e'
down_revision = '706d69dab38f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('environment_variables', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('detected_env_vars', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'detected_env_vars')
    op.drop_column('projects', 'environment_variables')
    # ### end Alembic commands ###