"""Add ssh_private_key to users table

Revision ID: e5ca68a75faa
Revises: b89a73584198
Create Date: 2025-08-26 02:36:34.598026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ca68a75faa'
down_revision = 'b89a73584198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###